workflow:
  name: default
  version: 2
  start: design_draft
phases:
  code_fix:
    type: execute
    prompt: review.fix.md
    description: Apply fixes from code review
    transitions:
      - to: code_review
        auto: true
  code_review:
    type: evaluate
    prompt: review.evaluate.md
    description: Review code changes (read-only)
    transitions:
      - to: code_fix
        when: status.reviewNeedsChanges == true
      - to: complete
        when: status.reviewClean == true
  complete:
    type: terminal
    description: Workflow complete
    transitions: []
  completeness_verification:
    type: evaluate
    prompt: verify.completeness.md
    description: Verify complete implementation against design
    transitions:
      - to: implement_task
        when: status.missingWork == true
      - to: prepare_pr
        when: status.implementationComplete == true
  design_draft:
    type: execute
    provider: codex
    prompt: design.draft.md
    description: Create initial design document
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.2
  design_edit:
    type: execute
    provider: codex
    prompt: design.edit.md
    description: Apply changes from design review
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.2
  design_review:
    type: evaluate
    prompt: design.review.md
    description: Review design document (read-only)
    transitions:
      - to: design_edit
        when: status.designNeedsChanges == true
      - to: task_decomposition
        when: status.designApproved == true
  fix_ci:
    type: execute
    prompt: ci.fix.md
    description: Fix commit/push failures (lint, pre-push hooks, etc)
    transitions:
      - to: task_spec_check
        auto: true
  implement_task:
    type: execute
    prompt: task.implement.md
    description: Implement current task
    transitions:
      - to: task_spec_check
        auto: true
  prepare_pr:
    type: execute
    prompt: pr.prepare.md
    description: Create pull request after all tasks complete
    transitions:
      - to: code_review
        when: status.prCreated == true
  task_decomposition:
    type: execute
    prompt: task.decompose.md
    description: Extract tasks from design document
    transitions:
      - to: implement_task
        when: status.taskDecompositionComplete == true
  task_spec_check:
    type: evaluate
    prompt: task.spec_check.md
    description: Verify task meets acceptance criteria
    transitions:
      - to: fix_ci
        when: status.commitFailed == true
        priority: 1
      - to: fix_ci
        when: status.pushFailed == true
        priority: 2
      - to: implement_task
        when: status.taskFailed == true
        priority: 3
      - to: implement_task
        when: status.taskPassed == true and status.hasMoreTasks == true
        priority: 4
      - to: completeness_verification
        when: status.allTasksComplete == true
        priority: 5
