workflow:
  name: default
  version: 2
  start: design_draft

phases:
  # Design phases
  design_draft:
    prompt: design.draft.md
    type: execute
    description: Create initial design document
    transitions:
      - to: design_review
        auto: true

  design_review:
    prompt: design.review.md
    type: evaluate
    description: Review design document (read-only)
    allowed_writes:
      - ".jeeves/*"
    transitions:
      - to: design_edit
        when: "status.designNeedsChanges == true"
      - to: task_decomposition
        when: "status.designApproved == true"

  design_edit:
    prompt: design.edit.md
    type: execute
    description: Apply changes from design review
    transitions:
      - to: design_review
        auto: true

  # Task decomposition phase
  task_decomposition:
    prompt: task.decompose.md
    type: execute
    description: Extract tasks from design document
    transitions:
      - to: implement_task
        when: "status.taskDecompositionComplete == true"

  # Task implementation loop
  implement_task:
    prompt: task.implement.md
    type: execute
    description: Implement current task
    transitions:
      - to: task_spec_check
        auto: true

  task_spec_check:
    prompt: task.spec_check.md
    type: evaluate
    description: Verify task meets acceptance criteria
    allowed_writes:
      - ".jeeves/*"
    transitions:
      - to: implement_task
        when: "status.taskFailed == true"
      - to: implement_task
        when: "status.taskPassed == true and status.hasMoreTasks == true"
      - to: completeness_verification
        when: "status.allTasksComplete == true"

  # Final completeness check
  completeness_verification:
    prompt: verify.completeness.md
    type: evaluate
    description: Verify complete implementation against design
    allowed_writes:
      - ".jeeves/*"
    transitions:
      - to: implement_task
        when: "status.missingWork == true"
      - to: code_review
        when: "status.implementationComplete == true"

  # Code review loop
  code_review:
    prompt: review.evaluate.md
    type: evaluate
    description: Review code changes (read-only)
    allowed_writes:
      - ".jeeves/*"
    transitions:
      - to: code_fix
        when: "status.reviewNeedsChanges == true"
      - to: complete
        when: "status.reviewClean == true"

  code_fix:
    prompt: review.fix.md
    type: execute
    description: Apply fixes from code review
    transitions:
      - to: code_review
        auto: true

  # Terminal state
  complete:
    type: terminal
    description: Workflow complete
