workflow:
  name: default
  version: 3
  start: design_classify
  default_provider: codex
  default_model: gpt-5.3-codex
  default_reasoning_effort: xhigh
phases:
  code_fix:
    type: execute
    provider: claude
    prompt: review.fix.md
    description: Apply fixes from code review
    transitions:
      - to: code_review
        auto: true
    model: opus
    thinking_budget: max
  code_review:
    type: evaluate
    provider: codex
    prompt: review.evaluate.md
    description: Review code changes (read-only)
    transitions:
      - to: code_fix
        when: status.reviewNeedsChanges == true
      - to: complete
        when: status.reviewClean == true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  complete:
    type: terminal
    description: Workflow complete
    transitions: []
  completeness_verification:
    type: evaluate
    provider: codex
    prompt: verify.completeness.md
    description: Verify complete implementation against design
    transitions:
      - to: implement_task
        when: status.missingWork == true
      - to: prepare_pr
        when: status.implementationComplete == true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_api:
    type: execute
    provider: codex
    prompt: design.api.md
    description: Design interfaces, endpoints, and contracts
    transitions:
      - to: design_data
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_classify:
    type: execute
    provider: codex
    prompt: design.classify.md
    description: Classify feature types and establish scope
    transitions:
      - to: design_workflow
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_data:
    type: execute
    provider: codex
    prompt: design.data.md
    description: Design schemas, migrations, and data handling
    transitions:
      - to: design_plan
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_edit:
    type: execute
    provider: codex
    prompt: design.edit.md
    description: Apply changes from design review
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: high
  design_plan:
    type: execute
    provider: codex
    prompt: design.plan.md
    description: Break down design into implementable tasks
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_review:
    type: evaluate
    provider: codex
    prompt: design.review.md
    description: Review complete design document (read-only)
    transitions:
      - to: design_edit
        when: status.designNeedsChanges == true
      - to: pre_implementation_check
        when: status.designApproved == true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  design_workflow:
    type: execute
    provider: codex
    prompt: design.workflow.md
    description: Design state transitions and error handling
    transitions:
      - to: design_api
        auto: true
    model: gpt-5.3-codex
    reasoning_effort: xhigh
  fix_ci:
    type: execute
    provider: claude
    prompt: ci.fix.md
    description: Fix commit/push failures (lint, pre-push hooks, etc)
    transitions:
      - to: task_spec_check
        auto: true
    model: opus
  implement_task:
    type: execute
    provider: claude
    prompt: task.implement.md
    description: Implement current task
    transitions:
      - to: implement_task
        when: control.restartPhase == true
      - to: task_spec_check
        auto: true
        priority: 1
    model: opus
    thinking_budget: max
  pre_implementation_check:
    type: evaluate
    provider: codex
    prompt: verify.pre_implementation.md
    description: Verify task coverage before implementation
    transitions:
      - to: design_edit
        when: status.preCheckFailed == true
      - to: implement_task
        when: status.preCheckPassed == true
    model: gpt-5.3-codex
    reasoning_effort: high
  prepare_pr:
    type: execute
    provider: claude
    prompt: pr.prepare.md
    description: Create pull request after all tasks complete
    transitions:
      - to: code_review
        when: status.prCreated == true
    model: sonnet
    thinking_budget: max
  task_spec_check:
    type: evaluate
    provider: codex
    prompt: task.spec_check.md
    description: Verify task meets acceptance criteria
    transitions:
      - to: fix_ci
        when: status.commitFailed == true
        priority: 1
      - to: fix_ci
        when: status.pushFailed == true
        priority: 2
      - to: implement_task
        when: status.taskFailed == true
        priority: 3
      - to: implement_task
        when: status.taskPassed == true and status.hasMoreTasks == true
        priority: 4
      - to: completeness_verification
        when: status.allTasksComplete == true
        priority: 5
    model: gpt-5.3-codex
    reasoning_effort: xhigh
