workflow:
  name: default
  version: 2
  start: design_draft
  default_provider: codex
  default_model: gpt-5.2
  default_reasoning_effort: xhigh
phases:
  code_fix:
    type: execute
    provider: claude
    prompt: review.fix.md
    description: Apply fixes from code review
    transitions:
      - to: code_review
        auto: true
    model: opus
    thinking_budget: max
  code_review:
    type: evaluate
    provider: codex
    prompt: review.evaluate.md
    description: Review code changes (read-only)
    transitions:
      - to: code_fix
        when: status.reviewNeedsChanges == true
      - to: complete
        when: status.reviewClean == true
    model: gpt-5.2
    reasoning_effort: high
  complete:
    type: terminal
    description: Workflow complete
    transitions: []
  completeness_verification:
    type: evaluate
    provider: codex
    prompt: verify.completeness.md
    description: Verify complete implementation against design
    transitions:
      - to: implement_task
        when: status.missingWork == true
      - to: prepare_pr
        when: status.implementationComplete == true
    model: gpt-5.2
    reasoning_effort: high
  design_draft:
    type: execute
    provider: codex
    prompt: design.draft.md
    description: Create initial design document
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.2
    reasoning_effort: xhigh
  design_edit:
    type: execute
    provider: codex
    prompt: design.edit.md
    description: Apply changes from design review
    transitions:
      - to: design_review
        auto: true
    model: gpt-5.2
    reasoning_effort: high
  design_review:
    type: evaluate
    provider: codex
    prompt: design.review.md
    description: Review design document (read-only)
    transitions:
      - to: design_edit
        when: status.designNeedsChanges == true
      - to: task_decomposition
        when: status.designApproved == true
    model: gpt-5.2
    reasoning_effort: high
  fix_ci:
    type: execute
    provider: claude
    prompt: ci.fix.md
    description: Fix commit/push failures (lint, pre-push hooks, etc)
    transitions:
      - to: task_spec_check
        auto: true
    model: opus
  implement_task:
    type: execute
    provider: claude
    prompt: task.implement.md
    description: Implement current task
    transitions:
      - to: task_spec_check
        auto: true
    model: opus
    thinking_budget: max
  prepare_pr:
    type: execute
    provider: claude
    prompt: pr.prepare.md
    description: Create pull request after all tasks complete
    transitions:
      - to: code_review
        when: status.prCreated == true
    model: sonnet
    thinking_budget: max
  pre_implementation_check:
    type: evaluate
    provider: codex
    prompt: verify.pre_implementation.md
    description: Verify task coverage before implementation
    transitions:
      - to: implement_task
        when: status.preCheckPassed == true
      - to: task_decomposition
        when: status.preCheckFailed == true
    model: gpt-5.2
    reasoning_effort: high
  task_decomposition:
    type: execute
    provider: claude
    prompt: task.decompose.md
    description: Extract tasks from design document
    transitions:
      - to: pre_implementation_check
        when: status.taskDecompositionComplete == true
    model: haiku
    thinking_budget: max
  task_spec_check:
    type: evaluate
    provider: codex
    prompt: task.spec_check.md
    description: Verify task meets acceptance criteria
    transitions:
      - to: fix_ci
        when: status.commitFailed == true
        priority: 1
      - to: fix_ci
        when: status.pushFailed == true
        priority: 2
      - to: implement_task
        when: status.taskFailed == true
        priority: 3
      - to: implement_task
        when: status.taskPassed == true and status.hasMoreTasks == true
        priority: 4
      - to: completeness_verification
        when: status.allTasksComplete == true
        priority: 5
    model: gpt-5.2
    reasoning_effort: high
